name: Firebase Deployment

'on':
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

env:
  API_KEY: ${{ secrets.FB_API_KEY }}
  AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
  PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
  MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
  APP_ID: ${{ secrets.FB_APP_ID }}
  MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}

jobs:
  fe-build-and-deploy:
    name: Dev Frontend - Build and Deploy
    runs-on: ubuntu-latest
    steps:
        # Initial pipeline setup 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Initialize Node and Cache Dependencies
        uses: actions/setup-node@master
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
        # Install node dependencies
      - name: Install Dependencies
        run: npm install

        # Build angular app with dev configuration
      - name: Build dev app
        run: npm run build

        # Archive dev artifact
      - name: Archive dev artifact
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: ./dist/consistency-drives-results

        # Deploy app to Firebase
      - name: Deploy app to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FB_SA_KEY }}
          PROJECT_ID: "consistency-drives-results"
          PROJECT_PATH: "./"
      - run: echo "If you made it this far, high fives all around!"
 